### ISSUE TITLE
Exception when reading Ubidots variable value 

### ISSUE THREAD

**Issue by jdavidleo** [ubidots/ubidots-c-sharp#1]
Hi! I would like to thank you for your great Ubidots library for c#.

I'm facing a problem when accessing the values in a variable using the GetValues() method, it throws an exception that says "Value cannot be null. Parameter name: value"

i'm using the method when user clicks a button. 

private void button2_Click(object sender, EventArgs e)
        {
            Variable mpy = Api.GetVariable("Variable ID");
            Value[] valores = mpy.GetValues();
            textBox1.Text = valores.ToString();
        }

thank you for your attention.

**Comment by juanda95** [comment]
Thanks!
I just found the error. I'll fix it.

**Comment by juanda95** [comment]
Must be updated in NuGet in a moment :smile:

**Comment by jdavidleo** [comment]
thanks Partner! (Y)
